spring:
  application:
    name: Zomato-Clone-API

  #
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#APPLICATION CONFIGURATION
zomato:
  base_url: /api/v1
  jwt:
    secret: ${JWT_SECRET}

# CLOUDINARY CONFIGURATION
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  cloud_apikey: ${CLOUDINARY_API_KEY}
  cloud_api_secret: ${CLOUDINARY_API_SECRET}