spring:
  application:
    name: Zomato-Clone-API
  datasource:
    url: jdbc:/localhost:3306/zomato_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


